import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import './globals.css';
import BaseLayout from '@/components/layout';
import Sidebar from '@/components/layout/sidebar';
import { SocketProvider } from '@/components/context/SocketProvider';
import Topbar from '@/components/layout/topbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Long Process',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SocketProvider>
          <Theme accentColor='blue' grayColor='sand' radius='large'>
            <BaseLayout sidebar={<Sidebar />} topbar={<Topbar />}>
              {children}
            </BaseLayout>
          </Theme>
        </SocketProvider>
      </body>
    </html>
  );
}
